### ISSUE TITLE
Setting variable to layout template as a global

### ISSUE THREAD

**Issue by hkulekci** [zendframework/zend-expressive-twigrenderer#24]
I am trying to inject some of my session or user information to my layout to change my header information. I did not find any way to implement with twig. I know, there is global variable to inject but I have some logic. My variables are changeable according to the logic, not static. 

I try to extend `TwigRendererFactory` to inject my variable. I had to copy all of the factory content new one. I don't want to do it. Is there any other way to reach `TwigEnvironment`or should I access reach?

**Comment by hkulekci** [comment]
I found the solution. Choose a middleware and inject `TwigRenderer` after that use `addDefaultParam` method with `TemplateRendererInterface::TEMPLATE_ALL` parameter. 

```
class SampleMiddleware
{
    /**
     * @var TemplateRendererInterface
     */
    protected $template;

    public function __construct(TemplateRendererInterface $template)
    {
        $this->template  = $template;
    }

    public function __invoke(ServerRequestInterface $request, ResponseInterface $response, callable $next = null)
    {
        $this->template->addDefaultParam(TemplateRendererInterface::TEMPLATE_ALL, 'haydar', "Uber");
        
        if ($next) {
            return $next($request, $response);
        }
        return $response;
    }
}
```

Sorry for noise.

**Comment by ozzpy** [comment]
How can I pass a variable from HomeAction.php to layout/default.php ??? and not to template file app::home-page.

**Comment by hkulekci** [comment]
use below:

```
$this->template->addDefaultParam(TemplateRendererInterface::TEMPLATE_ALL, 'haydar', 'Uber');
```

**Comment by ozzpy** [comment]
but, this only pass the variable to template and not to layout. on layout I cant show 
`echo $this->haydar` or `echo $haydar`, only on template file.
I want to pass the variable from Middleware Action to layout file and not to template.
templates/layout/default.phtml -> here. How can I do that?

https://github.com/zendframework/zend-expressive-twigrenderer/issues/35
