### ISSUE TITLE
How to pass a variable from HomeAction.php to layout/default.phtml and not to app::home-page template

### ISSUE THREAD

**Issue by ozzpy** [zendframework/zend-expressive-twigrenderer#35]

**Comment by ozzpy** [comment]
I try this  and work fine  on app:home-page template, but I cant use this on layout/default.php.
`$this->template->addDefaultParam(Template\TemplateRendererInterface::TEMPLATE_ALL,'whoisI','Rafael');
        return new HtmlResponse($this->template->render('app::home-page', $data));`

**Comment by ozzpy** [comment]
In ZF3 I got all variable on layout.phtml from Any ControllerAction.

**Comment by geerteltink** [comment]
For questions we have [slack](https://zendframework-slack.herokuapp.com/) and [forums](https://discourse.zendframework.com/).

Besides that, I think you are asking a question meant for zend-expressive-zendviewrenderer. 

I know that for the twig and plates renderer it works exactly as your example code. As I don't use zend-view myself, I can't help you with that. I suggest to try slack or our forums or report a bug at zendframework/zend-expressive-zendviewrenderer if it isn't working as expected.
