### ISSUE TITLE
How get container in twig base layout

### ISSUE THREAD

**Issue by LeikoDmitry** [zendframework/zend-expressive-twigrenderer#40]
Hello, How get container in twig base layout?

**Comment by geerteltink** [comment]
Issues are for reporting bugs. Questions can be asked at our [forums](https://discourse.zendframework.com/) or [slack](https://zendframework-slack.herokuapp.com/).

You cannot get the container in a template. You should inject the vars you need or create extensions that would do what you want to do.

In general injecting the entire container anywhere is considered bad practice.
