### ISSUE TITLE
Refactor the default Twig extension into its own factory

### ISSUE THREAD

**Issue by geerteltink** [zendframework/zend-expressive-twigrenderer#41]
Why did I do this?

https://github.com/zendframework/zend-expressive-twigrenderer/blob/8de4ced7e987c299f8136bb094f27393a6407999/src/TwigEnvironmentFactory.php#L106-L115

This way you can't override the default extension and it's registered functions. Moving this into its own factory and use the default `twig -> extensions` config key would be a better approach.

**Comment by weierophinney** [comment]
Fixed in #43
