### ISSUE TITLE
How to include stylesheets?

### ISSUE THREAD

**Issue by thalysonalexr** [zendframework/zend-expressive-twigrenderer#47]
I'm trying to include the stylesheets in my twig template that are lying within the default directory created by the `/templates` skeleton. There I created a `/templates/assets` directory. Create a block `{% block stylesheets%} {% endblock%}` in my default layout inside the header tag and extended to use the other template that is inside the `/templates/app` directory. I'm trying to include this in my style.css file as follows:
```
{% block stylesheets %}
    {{ parent() }}

    <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/style.css') }}">
{% endblock %}
```
The skeleton looks like this:

```
templates/
     /app
     /assets
        /css
            style.css
     /error
     /layout
```
My question is, what do I have to configure for my template to find the .css file? When I make a request for error 404 because it simply adds the `assets/css/style.css` path in the current route.

**Comment by geerteltink** [comment]
You need to place your assets in the public directory: `/path-to-project/public/assets/css/style.css`

I usually have my css files in the templates or a resources dir for development. With a script I generate compressed css files in the public dir. Same with images and javascript. 

https://github.com/xtreamwayz/xtreamwayz.com/blob/9e6f53a0d28b557b80a6d34cb0dd845d2938f3d3/Makefile#L20-L37

Other solution could be to symlink the assests dir into the public dir.

**Comment by froschdesign** [comment]
@xtreamwayz 
Do we have an overview of the (default) directory structure in the documentation? I can not find anything?

**Comment by geerteltink** [comment]
> I can not find anything?

Because there is no official default directory structure? (@weierophinney?) There have been discussions in the past and the skeleton is based on that. But basically everyone is free to create a structure as they like.

**Comment by froschdesign** [comment]
@xtreamwayz 
The background of my question: The skeleton creates a directory structure and with a short description of this structure the current question would be avoided.

**Comment by thalysonalexr** [comment]
@xtreamwayz  Thanks man! The example of your source code was more than enlightening!
