### ISSUE TITLE
[Very Minor] consistency beetween both Exception message in the code

### ISSUE THREAD

**Issue by ncou** [zendframework/zend-expressive-twigrenderer#49]
Hi,

Nice piece of code. I just found something (very very very minor) in the class TwigEnvironmentFactory. It's the consistency beetween both Exception message when the object type has not the right interface.

In the first message, the interface name is hardcoded in the string, in the second message it use a parameter in the sprintf function using "Interface::class".
I think both of the messages should use the ::class parameter.

What do you think ? i could push a PR if you want.

https://github.com/zendframework/zend-expressive-twigrenderer/blob/master/src/TwigEnvironmentFactory.php#L198

https://github.com/zendframework/zend-expressive-twigrenderer/blob/master/src/TwigEnvironmentFactory.php#L237

**Comment by weierophinney** [comment]
A PR would be quite welcome; thanks!

**Comment by ncou** [comment]
I made the PR (https://github.com/zendframework/zend-expressive-twigrenderer/pull/50).
Let me know if all is correct.

By the way I have spot some missing @param in the docbloc for the Container parameter. Not sure if it's a missing or if zend coding standard allow to not add all the @param for a given function.

I also have some failures when i try to run the tests, because the line endings caracter are not equals ('\r\n' vs '\n') but it's perhaps because i am using Windows OS and not some Linux OS (travis-ci seems to work fine). But i didn't really investigate.

**Comment by michalbundyra** [comment]
I see PR #50 has been merged so this can be closed now. Thanks @ncou!
