### ISSUE TITLE
enable 'strict_variables' through config files

### ISSUE THREAD

**Issue by bernard-ng** [zendframework/zend-expressive-twigrenderer#55]
Would it be possible to activate the mode '**strict_variables**' in the **TwigEnvironmentFactory** via the configuration? rather than according to the development mode

**Comment by michalbundyra** [comment]
@bernard-ng  Can you submit PR with this additional configuration option, please?
Please remember to add unit tests. Thanks !

**Comment by bernard-ng** [comment]
#56
