### ISSUE TITLE
TwigRendererFactory supports ambiguous configuration for key twig and templates

### ISSUE THREAD

**Issue by sandrokeil** [zendframework/zend-expressive-twigrenderer#7]
The configuration structure is

``` php
return [
    'debug' => boolean,
    'templates' => [
        'extension' => 'file extension used by templates; defaults to html.twig',
        'paths' => [
            // namespace / path pairs
            //
            // Numeric namespaces imply the default/main namespace. Paths may be
            // strings or arrays of string paths to associate with the namespace.
        ],
    ],
    'twig' => [
        'cache_dir' => 'path to cached templates',
        'assets_url' => 'base URL for assets',
        'assets_version' => 'base version for assets',
        'extensions' => [
            // extension service names or instances
        ],
    ],
];
```

But you can also put all keys under `twig` to the `templates` key and vice versa. Because of the `TwigRendererFactory::mergeConfig()` method. Is this really an expected behavior? This is used in [`\ZendTest\Expressive\Twig\TwigRendererFactoryTest::testCanSpecifyCacheDirectoryViaConfiguration`](https://github.com/zendframework/zend-expressive-twigrenderer/blob/e1dd1744bf9ba5ec364fc1320566699d04f407c4/test/TwigRendererFactoryTest.php#L154) and [`\ZendTest\Expressive\Twig\TwigRendererFactoryTest::testUsesAssetsConfigurationWhenAddingTwigExtension`](https://github.com/zendframework/zend-expressive-twigrenderer/blob/e1dd1744bf9ba5ec364fc1320566699d04f407c4/test/TwigRendererFactoryTest.php#L182).

This could confuse people and could leads to an unexpected behavior, if this config is shared and used by other factories.

**Comment by geerteltink** [comment]
This is expected and was changed in [0.3.0](https://github.com/zendframework/zend-expressive-twigrenderer/blob/master/CHANGELOG.md#030---2015-12-02).

> Deprecated usage of the cache_dir and assets_\* sub-keys under the templates top-level key, in favor of positioning them beneath a twig top-level key. As templates and twig values are merged, however, this change should not affect end-users.

I think the tests should be adjusted to the preferred twig key.
